[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "zbar"]

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "source /app/.venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /app/.venv/bin/activate && python FRONTEND/frontend.py"
