[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "zbar"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python FRONTEND/frontend.py"
